[package]
name = "zopfli"
version = "0.4.0"
authors = ["Carol (Nichols || Goulding) <carol.nichols@gmail.com>"]
description = "A Rust implementation of the Zopfli compression algorithm."
license = "Apache-2.0"
keywords = ["compression"]
homepage = "https://github.com/carols10cents/zopfli"
repository = "https://github.com/carols10cents/zopfli"
readme = "README.md"
categories = ["compression"]
exclude = ["test/*"]

[dependencies]
crc = "2.0.0"
adler32 = "1.0.3"
byteorder = "1.2.6"
typed-arena = "2.0.1"

[profile.release]
debug = true
